/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tecsec_OpenVEIL_RequestResults */

#ifndef _Included_com_tecsec_OpenVEIL_RequestResults
#define _Included_com_tecsec_OpenVEIL_RequestResults
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
